# Generated by Django 4.2.30 on 2026-04-25 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('business_size', models.CharField(blank=True, choices=[('solo', 'Solo / Freelancer'), ('small', 'Small (1–10 employees)'), ('medium', 'Medium (11–100 employees)'), ('large', 'Large (101–500 employees)'), ('enterprise', 'Enterprise (500+)')], max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('ecommerce', 'E-commerce / Retail'), ('saas', 'SaaS / Technology'), ('fintech', 'Fintech / Banking'), ('healthcare', 'Healthcare'), ('logistics', 'Logistics / Delivery'), ('education', 'Education'), ('agency', 'Marketing Agency'), ('other', 'Other')], max_length=30)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('bsp_key', models.CharField(blank=True, max_length=50)),
                ('marketing_vol', models.IntegerField(default=0)),
                ('utility_vol', models.IntegerField(default=0)),
                ('auth_vol', models.IntegerField(default=0)),
                ('service_vol', models.IntegerField(default=0)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meta_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
